# Generated by Django 3.2.16 on 2023-03-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20230303_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='details_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
