# Generated by Django 3.2.16 on 2023-03-13 20:55

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20230309_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(default='text'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='descripton_long',
            field=tinymce.models.HTMLField(default=''),
            preserve_default=False,
        ),
    ]
