# Generated by Django 3.2.16 on 2023-03-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0011_alter_image_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='place',
            name='lng',
            field=models.FloatField(default=0),
        ),
    ]
