# Generated by Django 3.2.16 on 2023-03-15 09:37

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0013_alter_place_description_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='place',
            name='lng',
            field=models.FloatField(),
        ),
    ]
